name: Gideondevilliers.com
favicon: null
layout_spectrum: 0.7897982487920672
typography_spectrum: 0.04740360798314214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2471122364513576
  lightness: 0.28669323842041194
  saturation: 0.611443433444947
  rhythmicContrast: 0.8305321563966572
purpose: []
