name: Gideondevilliers.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74571
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef2f1'
    - '#9ea7a6'
    - '#01080e'
    - '#073956'
    - '#b5795e'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
